In [20]:
import torch
from past.builtins import reduce
from torch.distributions import Normal
import numpy as np

In [11]:
N = Normal(loc=torch.tensor(0.5, dtype=torch.float), 
           scale=torch.tensor(1, dtype=torch.float))


In [13]:
print(N.log_prob(torch.tensor(0.1, dtype=torch.float)))
print(-((0.1 - 0.5)**2 / (2 * 1))  - np.log(2 * np.pi * 1))

tensor(-0.9989)
-0.08000000000000002


In [16]:
T = torch.tensor([6, 3])
print(2*T)




tensor([12,  6])


In [44]:
seq = torch.tensor([1, 2, 3, 4], dtype=torch.float)
target_cs = torch.cumsum(seq, dim=0) 
target_loop = torch.zeros_like(seq)
for i in range(seq.shape[0] - 1):
    target_loop[i] = torch.sum(seq[:i+1])
    

In [38]:
torch.sum(seq[:2])



tensor(3.)

In [62]:
t = torch.tensor([1,2,3,4], dtype=torch.float).expand(3,4)
print(t)



tensor([[1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.]])


In [66]:
print(t[0,:])
print(t[0,:].flip(dims=[0]))


tensor([1., 2., 3., 4.])
tensor([4., 3., 2., 1.])
